version: '3'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  huey_consumer:
    build:
      context: .
      dockerfile: Dockerfile
    command: python huey_consumer.py routers.data_router.huey -w 4
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
