apiVersion: apps/v1
kind: Deployment
metadata:
  name: huey-consumer-deployment
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: huey-consumer
  template:
    metadata:
      labels:
        app: huey-consumer
    spec:
      containers:
      - name: huey-consumer
        image: tawheed758/cambai-huey_consumer:latest
        command: ["python", "huey_consumer.py", "routers.data_router.huey", "-w", "4"]
